gave
exceptions.Exception: External dependencies not satisfied: xorg-input versiyon >= 7.3

instead of

exceptions.Exception: Dış bağımlılıklar sağlanamadı